### ISSUE TITLE
simplify config export

### ISSUE THREAD

**Issue by mdrmike** [thinktandem/migration_boilerplate#2]
Unless I'm missing something.... 

In the `readme.md` I think the following lines can be simplified. In other words, I don't see a need to separately manually ssh into lando app just to copy files.  Instead, just export directly to the app. 

```
lando drush config-export --destination=/tmp/migrate
lando ssh -s appserver -u root
cp /tmp/migrate/migrate_plus.* /app/path/to/migration_boilerplate/unused_config
chown -R www-data:www-data /app/path/to/migration_boilerplate/unused_config
exit
```
to

```
lando drush config-export --destination=/app/path/to/migration_boilerplate/unused_config
```

in my .lando.yml I am using this line

`lando drush config-export --destination=/app/web/modules/contrib/migration_boilerplate`/unused_config

**Comment by labboy0276** [comment]
The reason for this is we don't want all the config objects to get thrown into the migration_boilerplate/unused_config.  By doing it the way I outlined, you only populate the folder with the migration config items.

You can do it your way, but then you have to manually delete a whole bunch of stuff @mdrmike

**Comment by mdrmike** [comment]
Ah, thanks! That wasn't clear to me, but that makes sense. I'm already a lando user so I was happy I found this module due to (otherwise poor) [documentation on migration with drush](https://www.drupal.org/docs/8/upgrade/upgrade-using-drush). 

I'll have to dig through all those files,,, still unsure what some of these extra migrate modules do ... soo little documentation. I'm just trying to migrate a simple d7 that core migrate couldn't migrate media, even though most of the modules are now in core are exist in D8. good times

**Comment by labboy0276** [comment]
@mdrmike come to the webinar on Friday and I will show you the ways: https://us02web.zoom.us/webinar/register/WN_xWFjNrQtTNK2ZeAMu6ePmw

**Comment by mdrmike** [comment]
Ha! I'm cleaning up browser tabs and this has been open for a month... I wrote the following but never submitted. Might save someone some time. 

Oh, and the webinar and follow-up [blog posts on Drupal Migration](https://thinktandem.io/blog/2020/05/12/lando-migration-webinar-part-2-followup/) were great! 

----
Just in case anyone comes looking in the future, I _was_ able to do this with only two lines of code.

```sh
lando drush config-export -q -y --destination=/app/web/modules/contrib/migration_boilerplate/unused_config
find "web/modules/contrib/migration_boilerplate/unused_config" -type f -not -name 'migrate_plus.*' -delete
```
_**Note:** `chown` was only required because the example uses `lando ssh` to login as `root`; which is unnecessary._



My ultimate setup was a `.lando.yml` a config folder with migration_boilerplate, and a couple shell scripts to run after appserver has been created/rebuilt. (I also have a `pre-rebuild` event to cleanup and wipe drupal on a rebuild). I use composer to create a fresh install of Drupal. first downloading to a clean folder called, `json`, then moving to lando working directory

```yml

  appserver:
    run:
      - echo "Install Drupal 8..."
      - composer create-project --no-install --remove-vcs drupal/recommended-project json
      - mv json/composer.json json/composer.lock /app
      - rmdir json
      - composer require --sort-packages -- 'drush/drush:^9.7' drupal/core-recommended  drupal/bootstrap_barrio  drupal/bootstrap_sass  drupal/views_bootstrap  drupal/admin_toolbar  drupal/entity  drupal/entity_reference_revisions  drupal/libraries  drupal/redirect  drupal/simple_sitemap  drupal/webform  drupal/ctools drupal/checklistapi drupal/diff drupal/fontawesome drupal/google_analytics drupal/metatag drupal/pathauto drupal/redirect drupal/scheduler drupal/seo_checklist drupal/token drupal/devel drupal/twig_tweak drupal/snippet_manager drupal/eu_cookie_compliance drupal/addtoany drupal/views_slideshow drupal/gutenberg drupal/hacked drupal/draggableviews drupal/flexslider drupal/term_merge drupal/module_filter 'drupal/migrate_plus:^4.2' 'drupal/migrate_tools:^4.5' 'drupal/migrate_upgrade' 'drupal/upgrade_status:^2.0' 'drupal/migrate_manifest' 'drupal/migrate_file_to_media'
      - drush si minimal -y --db-url=mysql://drupal8:drupal8@database:3306/drupal8 --site-name='Red Door Living' --account-mail=webmaster-rdl@MediaDoneRight.com
```

**Comment by mdrmike** [comment]
Ha! I'm cleaning up browser tabs and this has been open for a month... I wrote the following but never submitted. Might save someone some time. 

Oh, and the webinar and follow-up [blog posts on Drupal Migration](https://thinktandem.io/blog/2020/05/12/lando-migration-webinar-part-2-followup/) were great! 

----
Just in case anyone comes looking in the future, I _was_ able to do this with only two lines of code.

```sh
lando drush config-export -q -y --destination=/app/web/modules/contrib/migration_boilerplate/unused_config
find "web/modules/contrib/migration_boilerplate/unused_config" -type f -not -name 'migrate_plus.*' -delete
```
_**Note:** `chown` was only required because the example uses `lando ssh` to login as `root`; which is unnecessary._



My ultimate setup was a `.lando.yml` a config folder with migration_boilerplate, and a couple shell scripts to run after appserver has been created/rebuilt. (I also have a `pre-rebuild` event to cleanup and wipe drupal on a rebuild). I use composer to create a fresh install of Drupal. first downloading to a clean folder called, `json`, then moving to lando working directory

```yml

  appserver:
    run:
      - echo "Install Drupal 8..."
      - composer create-project --no-install --remove-vcs drupal/recommended-project json
      - mv json/composer.json json/composer.lock /app
      - rmdir json
      - composer require --dev --sort-packages -- 'drush/drush:^9' 'drupal/migrate_plus:^4.2' 'drupal/migrate_tools:^4.5' 'drupal/migrate_upgrade' 'drupal/upgrade_status:^2.0'
      - drush si minimal -y --db-url=mysql://drupal8:drupal8@database:3306/drupal8
```
